name: Build Laravel docker image and push it to Dockerhub

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop

jobs:
  checking-out-repo:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout codes
        uses: actions/checkout@v3

  laravel-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Use the same codes
        working-directory: ${{ github.workspace }}

      - uses: shivammathur/setup-php@15c43e89cdef867065b0213be354c2841860869e
        with:
          php-version: '8.0'
      - name: Copy .env
        run: php -r "file_exists('.env') || copy('.env.example', '.env');"

      - name: Update composer
        run: composer update

      - name: Install Dependencies
        run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist

      - name: Generate key
        run: php artisan key:generate

      - name: Directory Permissions
        run: chmod -R 777 storage bootstrap/cache

  build-push-development:
    if: ${{ github.ref == 'refs/heads/develop' }}
    runs-on: ubuntu-latest
    steps:
      - name: Use the same codes
        working-directory: ${{ github.workspace }}

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN_DEVELOPMENT }}

      - name: Build and push to development repository
        if: ${{ github.ref == 'refs/heads/develop' }}
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: rayhandrin/retapolban_development:latest

  build-push-production:
    if: ${{ github.ref == 'refs/heads/main' }}
    runs-on: ubuntu-latest
    steps:
      - name: Use the same codes
        working-directory: ${{ github.workspace }}

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN_PRODUCTION }}

      - name: Build and push to production repository
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: rayhandrin/retapolban_production:latest
